// The desktop shell read as source: its commands agree, answer only the pult, and the door's settings are what tauri.conf.json ships.
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import test from "node:test";

const read = (path: string): Promise<string> => readFile(new URL(`../${path}`, import.meta.url), "utf8");
const SHELL = "tauri/src-tauri";
const sources = await Promise.all((await readdir(new URL(`../${SHELL}/src`, import.meta.url))).filter((name) => name.endsWith(".rs"))
    .map(async (name) => [name, await read(`${SHELL}/src/${name}`)] as const));
const lib = await read(`${SHELL}/src/lib.rs`);
const apps = await read(`${SHELL}/src/apps.rs`);
const conf = JSON.parse(await read(`${SHELL}/tauri.conf.json`)) as {
    app: { withGlobalTauri?: boolean; windows: { label: string; dragDropEnabled?: boolean; useHttpsScheme?: boolean }[]; security: { pattern?: { use?: string } } };
    bundle: { macOS?: { minimumSystemVersion?: string } };
};
const capability = JSON.parse(await read(`${SHELL}/capabilities/main.json`)) as { permissions: string[] };

// every #[tauri::command], with the body of its function
const commands = new Map(sources.flatMap(([, source]) =>
    [...source.matchAll(/#\[tauri::command\]\s*(?:pub(?:\(crate\))? )?(?:async )?fn (\w+)/g)].map((m) => {
        const body = source.slice(source.indexOf("{", m.index + m[0].length) + 1);
        return [m[1] as string, body.trimStart()] as const;
    })));
const kebab = (name: string): string => `allow-${name.replaceAll("_", "-")}`;

test("the shell declares, permits and registers exactly the same commands", async () => {
    const registered = /generate_handler!\[([^\]]*)\]/.exec(lib)?.[1]?.split(",").map((s) => s.trim().split("::").at(-1)).filter(Boolean).sort();
    const built = /\.commands\(&\[([^\]]*)\]\)/.exec(await read(`${SHELL}/build.rs`))?.[1]?.match(/"(\w+)"/g)?.map((s) => s.slice(1, -1)).sort();
    const declared = [...commands.keys()].sort();
    assert.deepEqual(registered, declared);
    assert.deepEqual(built, declared);
    assert.deepEqual(capability.permissions.filter((p) => !p.includes(":")).sort(), declared.map(kebab).sort());
    // tauri-build writes this git-ignored folder, so a clean clone has no generated permissions to go stale
    const autogenerated = new URL(`../${SHELL}/permissions/autogenerated`, import.meta.url);
    const generated = (existsSync(autogenerated) ? await readdir(autogenerated) : []).map((f) => f.replace(/\.toml$/, ""));
    for (const name of generated) assert.ok(commands.has(name), `a stale permission for ${name}`);
});

test("the pult invokes only the shell's own commands, and no plugin permission lets it reach past them", async () => {
    const files = (await readdir(new URL("../src", import.meta.url), { recursive: true })).filter((f) => /\.tsx?$/.test(f));
    const pult = await Promise.all(files.map((f) => read(`src/${f}`)));
    const invoked = pult.flatMap((source) => [...source.matchAll(/\b(?:invoke|tauriInvoke\(\)\?\.)\("([^"]+)"/g)].map((m) => m[1] as string));
    assert.ok(invoked.length > 0);
    for (const name of invoked) assert.ok(commands.has(name), `the pult invokes ${name}, which the shell does not declare`);
    assert.deepEqual(capability.permissions.filter((p) => p.includes(":")), []);
});

test("every command answers only the pult's own page", () => {
    for (const [name, body] of commands) assert.match(body, /^(crate::)?(apps::)?pult_only\(/, `${name} does not start with pult_only`);
});

test("the frame door's two halves meet: one eval hook, one host template, one upload cap", async () => {
    const pult = await read("src/mini-apps.ts");
    for (const source of [apps, pult]) {
        assert.match(source, /__mimiApps/);
        assert.match(source, /\{host\}/);
    }
    assert.match(apps, /const UPLOAD_MAX: usize = 64 \* 1024 \* 1024;/);
    assert.match(lib, /register_asynchronous_uri_scheme_protocol\(apps::SCHEME/);
});

test("the settings the door relies on are what tauri.conf.json ships", () => {
    const main = conf.app.windows.find((w) => w.label === "main");
    assert.equal(conf.app.withGlobalTauri, false, "no __TAURI__ global");
    // Tauri's isolation listener would forward a frame's {payload: {contentType, nonce, payload}} postMessage to IPC
    assert.notEqual(conf.app.security.pattern?.use, "isolation");
    // Tauri's own file drop handler swallows every HTML5 drop, so a drop-zone upload would never reach an app
    assert.equal(main?.dragDropEnabled, false);
    assert.equal(main?.useHttpsScheme, false);
    // Safari 16.4's WebKit: DecompressionStream, CSP3 script-src-elem and Sec-Fetch-* in every frame
    assert.equal(conf.bundle.macOS?.minimumSystemVersion, "13.3");
});
